# Generated by Django 4.1.2 on 2022-10-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0002_rename_receipts_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="expensecategory",
            name="number_of_receipts",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
