# Generated by Django 4.1.2 on 2022-10-20 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0004_alter_expensecategory_number_of_receipts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expensecategory",
            name="number_of_receipts",
        ),
    ]
