# Generated by Django 4.1.2 on 2022-10-20 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0006_expensecategory_number_of_receipts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expensecategory",
            old_name="number_of_receipts",
            new_name="number_of_receipts2",
        ),
        migrations.AlterField(
            model_name="receipt",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipts",
                to="receipts.expensecategory",
            ),
        ),
    ]
