# Generated by Django 4.1.2 on 2022-10-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "receipts",
            "0009_remove_expensecategory_number_of_receipts3_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="expensecategory",
            name="number_of_receipts",
            field=models.IntegerField(null=True),
        ),
    ]
