# Generated by Django 4.1.2 on 2022-10-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0013_expensecategory_alter_receipt_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expensecategory",
            name="number_of_receipts",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
